### ISSUE TITLE
I have a ImportError: '_has_colorama'

### ISSUE THREAD

**Issue by kibeomKim** [ElementAI/baal#204]
**Describe the bug**
To import baal package, I have an error like this.

Python 3.6.9 (default, Mar 15 2022, 13:55:28)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import baal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.local/lib/python3.6/site-packages/baal/__init__.py", line 3, in <module>
    from .utils.log_configuration import set_logger_config
  File "/home/USER/.local/lib/python3.6/site-packages/baal/utils/log_configuration.py", line 15, in <module>
    from structlog.dev import ConsoleRenderer, _has_colorama
ImportError: cannot import name '_has_colorama'

**Vesion (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python: 3.6.9
 - BaaL version: 1.3.2
 - colorama version: 0.4.4
 - torch version: 1.10.2
 - GPU Driver: 470.103.01
 - CUDA: 11.4

**Additional context**
Could you explain to me how to fix it?!
Thanks

**Comment by kibeomKim** [comment]
I fix it up with changing  from structlog==21.5.0 to 19.2.0

**Comment by Dref360** [comment]
Did this happen when doing `pip install baal` with the latest version? This should've been fixed already.
