### ISSUE TITLE
Tensor type error while running the PyTorch Lightning example with CUDA

### ISSUE THREAD

**Issue by luigifcruz** [ElementAI/baal#79]
**Describe the bug**
<details><summary>Crash Log</summary>
<p>

```
Traceback (most recent call last):                                                                                    
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/modelwrapper.py", line 444, in mc_
inference                                                                                                             
    out = model(data)                                                                                                 
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl        
    result = self.forward(*input, **kwargs)                                                                           
  File "experiments/pl_baal_example.py", line 48, in forward                                                          
    return self.vgg16(x)     
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)                
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torchvision/models/vgg.py", line 43, in forward             
    x = self.features(x)     
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)                
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)    
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)                
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward             
    return self._conv_forward(input, self.weight)          
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)              
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same              

The above exception was the direct cause of the following exception:                                                  

Traceback (most recent call last):                         
  File "experiments/pl_baal_example.py", line 181, in <module>                                                        
    main(HParams())          
  File "experiments/pl_baal_example.py", line 175, in main                                                            
    should_continue = loop.step()                          
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/active/active_loop.py", line 67, in step                       
    to_label = self.heuristic(probs)                       
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/active/heuristics/heuristics.py", line 209, in __call__        
    return self.get_ranks(predictions)                     
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/active/heuristics/heuristics.py", line 201, in get_ranks       
    scores = self.get_uncertainties_generator(predictions)                                                            
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/active/heuristics/heuristics.py", line 142, in get_uncertainties_generator                   
    for pred in predictions:                               
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/utils/pytorch_lightning.py", line 67, in predict_on_dataset_generator                        
    pred = self.model.predict_step(data, idx)              
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/utils/pytorch_lightning.py", line 28, in predict_step          
    out = mc_inference(self, data, self.hparams.iterations, self.hparams.replicate_in_memory)                         
  File "/home/luigi/anaconda3/lib/python3.7/site-packages/baal-1.2.0-py3.7.egg/baal/modelwrapper.py", line 449, in mc_inference                    
    Note that there will be some speed trade-offs''') from e                                                          
RuntimeError: CUDA ran out of memory while BaaL tried to replicate data. See the exception above.                     
            Use `replicate_in_memory=False` in order to reduce the memory requirements.                               
            Note that there will be some speed trade-offs    
```
</p>
</details>

**To Reproduce**
Running `experiments/pl_baal_example.py`.

**Vesion (please complete the following information):**
 - OS: Manjaro
 - Python: Python 3.7
 - BaaL version: master

**Comment by Dref360** [comment]
Pytorch Lightning seems to put the model back on CPU after training. Weird that we did not pick this up before merging.

I'll submit a PR today! Thank you for reporting the issue, it is greatly appreciated!

**Comment by luigifcruz** [comment]
Awesome, thanks! Great project!
