### ISSUE TITLE
DataParrallel does not work with BaaL PL

### ISSUE THREAD

**Issue by Dref360** [ElementAI/baal#86]
**Describe the bug**
If we use multiple gpus, `Trainer.get_model()` returns a `LightningDataParallel` and we can't get `pool_loader` from it.

**To Reproduce**
Use multiple gpus with the example.

Stack trace:
```
Traceback (most recent call last):
  File "experiments/mc_dropout_pl/mcd_cls_experiment.py", line 224, in <module>
    main()
  File "experiments/mc_dropout_pl/mcd_cls_experiment.py", line 218, in main
    should_continue = loop.step()
  File "/opt/conda/lib/python3.7/site-packages/baal/active/active_loop.py", line 67, in step
    to_label = self.heuristic(probs)
  File "/opt/conda/lib/python3.7/site-packages/baal/active/heuristics/heuristics.py", line 209, in __call__
    return self.get_ranks(predictions)
  File "/opt/conda/lib/python3.7/site-packages/baal/active/heuristics/heuristics.py", line 592, in get_ranks
    predictions = np.array([np.ones([t.shape[0]]) for t in predictions]).reshape([-1])
  File "/opt/conda/lib/python3.7/site-packages/baal/active/heuristics/heuristics.py", line 592, in <listcomp>
    predictions = np.array([np.ones([t.shape[0]]) for t in predictions]).reshape([-1])
  File "/opt/conda/lib/python3.7/site-packages/baal/utils/pytorch_lightning.py", line 93, in predict_on_dataset_generator
    dataloader = self.model.pool_loader()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'LightningDataParallel' object has no attribute 'pool_loader'
```

**Expected behavior**
Should work

**Vesion (please complete the following information):**
 - OS:Ubuntu
 - Python: 3.7
 - BaaL version: master

**Additional context**

**Comment by Dref360** [comment]
it was on my end.
